plugins = []
headers = []

[functions]

  [functions."*"]

[build]
publish = "/Users/hsinchucombat/Documents/Codex/2026-07-02/hcf-visual-lab-brand-growth-partner"
publishOrigin = "default"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[redirects]]
from = "/services"
to = "/services.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/works"
to = "/works.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/pricing"
to = "/pricing.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/seo-ai"
to = "/seo-ai.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/blog"
to = "/blog.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/contact"
to = "/contact.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]